### ISSUE TITLE
Question: code of GitHub copilot.

### ISSUE THREAD

**Issue by chirag127** [Kek5chen/Kek5chen#1]
I have already downloaded the extension from the Visual Studio Market place in the .VSIX file. and unzipped it ,Now I'm confused. What are these .wasm files and I tried to open the extension.js but it is not to get formatted. do you know how I can format it ? I am trying to understand how the github copilot works and what contents does it send to servers.

**Comment by Kek5chen** [comment]
You don't unzip VSIX files. You install them using the Visual Studio installer.

**Comment by chirag127** [comment]
> You don't unzip VSIX files. You install them using the Visual Studio installer.

I already have it installed . But i want to read it's code.

**Comment by Kek5chen** [comment]
Since I am not sure if what you are planning is even legal and not breaking any TOS, i will be providing no further support regarding this question.
