### ISSUE TITLE
Question: When should I start with C++

### ISSUE THREAD

**Issue by zentix07** [Kek5chen/Kek5chen#4]
When should I start with C++ ? I've learned Python, what should I do next?  I want to be a software engineer.

**Comment by Kek5chen** [comment]
Maybe get used to object oriented programming first using a more higher level language like C#. If you want to just jump straight into C++, there are also some good tutorials out there. I recommend *The Cherno*.

To your original question, just start whenever you feel like you want to.

**Comment by fr0st404** [comment]
Thank You for the fast comment, have a nice day
