### ISSUE TITLE
Question: [does this 42er deserve grademes vip membership?]

### ISSUE THREAD

**Issue by buggcatcher** [Kek5chen/Kek5chen#5]
Hi I have an exam rank 02 shortly and I would like to train with your software
thank you xoxo

**Comment by Kek5chen** [comment]
Hi. Thanks for reaching out, though unfortunately it's not my project. I'm just one of the contributors. You can contribute to the project too, which will automatically make you eligible for the vip membership. Small things like bug fixes, refactors, spelling correction and similar stuff is always appreciated.

**Comment by Kek5chen** [comment]
It's also open source, so you can just modify it however you want
